using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace XrCode
{
    public partial class UIGamePlay : BaseUI
    {	protected Button mWithdrawalBtn;	protected Button mPrizeDrawBtn;	protected Button mTaskBtn;	protected RectTransform mReddot;	protected Text mReddotText;	protected Button mSettingBtn;	protected Text mCurMoneyText;	protected RectTransform mWithdrawTip;	protected Text mWithdrawTipText;	protected Slider mSlider;	protected RectTransform mProgressWTip;	protected UICurLevelItem mCurLevelItem1;	protected UICurLevelItem mCurLevelItem2;	protected UICurLevelItem mCurLevelItem3;	protected UICurLevelItem mCurLevelItem4;	protected UICurLevelItem mCurLevelItem5;	protected Image mCurDir;	protected RectTransform mMap;	protected Button mTipBtn;	protected Text mTipCountText;	protected RectTransform mTipFuncIcon;	protected ShakeRotateLeftRight mTipFuncTip;	protected Button mRefushBtn;	protected Text mRefushCountText;	protected RectTransform mRefushFuncIcon;	protected ShakeRotateLeftRight mRefushFuncTip;	protected Button mRemoveBtn;	protected Text mRemoveCountText;	protected RectTransform mRemoveFuncIcon;	protected ShakeRotateLeftRight mRemoveFuncTip;	protected Button mCurMoneyBtn;	protected RectTransform mCurMoneyBtnRect;	protected Image mGamePlayMask;	protected RectTransform mCurMoneyIcon;
        protected override void LoadPanel()
        {
            base.LoadPanel();
            		mWithdrawalBtn = mTransform.Find("Top/WithdrawalBtn").GetComponent<Button>();		mPrizeDrawBtn = mTransform.Find("Top/PrizeDrawBtn").GetComponent<Button>();		mTaskBtn = mTransform.Find("Top/TaskBtn").GetComponent<Button>();		mReddot = mTransform.Find("Top/TaskBtn/Reddot").GetComponent<RectTransform>();		mReddotText = mTransform.Find("Top/TaskBtn/Reddot/ReddotText").GetComponent<Text>();		mSettingBtn = mTransform.Find("Top/SettingBtn").GetComponent<Button>();		mCurMoneyText = mTransform.Find("Top/CurMoneyBtn/CurMoneyText").GetComponent<Text>();		mWithdrawTip = mTransform.Find("Top/WithdrawTip").GetComponent<RectTransform>();		mWithdrawTipText = mTransform.Find("Top/WithdrawTip/WithdrawTipText").GetComponent<Text>();		mSlider = mTransform.Find("Top/LevelProgess/Slider").GetComponent<Slider>();		mProgressWTip = mTransform.Find("Top/LevelProgess/ProgressWTip").GetComponent<RectTransform>();		mCurLevelItem1 = mTransform.Find("Top/LevelProgess/Slider/LevelsProgressIcons/CurLevelItem1").GetComponent<UICurLevelItem>();		mCurLevelItem2 = mTransform.Find("Top/LevelProgess/Slider/LevelsProgressIcons/CurLevelItem2").GetComponent<UICurLevelItem>();		mCurLevelItem3 = mTransform.Find("Top/LevelProgess/Slider/LevelsProgressIcons/CurLevelItem3").GetComponent<UICurLevelItem>();		mCurLevelItem4 = mTransform.Find("Top/LevelProgess/Slider/LevelsProgressIcons/CurLevelItem4").GetComponent<UICurLevelItem>();		mCurLevelItem5 = mTransform.Find("Top/LevelProgess/Slider/LevelsProgressIcons/CurLevelItem5").GetComponent<UICurLevelItem>();		mCurDir = mTransform.Find("Top/CurDir").GetComponent<Image>();		mMap = mTransform.Find("Center/Map").GetComponent<RectTransform>();		mTipBtn = mTransform.Find("Bottom/Funcs/TipBtn").GetComponent<Button>();		mTipCountText = mTransform.Find("Bottom/Funcs/TipBtn/Count/TipCountText").GetComponent<Text>();		mTipFuncIcon = mTransform.Find("Bottom/Funcs/TipBtn/TipFuncIcon").GetComponent<RectTransform>();		mTipFuncTip = mTransform.Find("Bottom/Funcs/TipBtn/TipFuncTip").GetComponent<ShakeRotateLeftRight>();		mRefushBtn = mTransform.Find("Bottom/Funcs/RefushBtn").GetComponent<Button>();		mRefushCountText = mTransform.Find("Bottom/Funcs/RefushBtn/Count/RefushCountText").GetComponent<Text>();		mRefushFuncIcon = mTransform.Find("Bottom/Funcs/RefushBtn/RefushFuncIcon").GetComponent<RectTransform>();		mRefushFuncTip = mTransform.Find("Bottom/Funcs/RefushBtn/RefushFuncTip").GetComponent<ShakeRotateLeftRight>();		mRemoveBtn = mTransform.Find("Bottom/Funcs/RemoveBtn").GetComponent<Button>();		mRemoveCountText = mTransform.Find("Bottom/Funcs/RemoveBtn/Count/RemoveCountText").GetComponent<Text>();		mRemoveFuncIcon = mTransform.Find("Bottom/Funcs/RemoveBtn/RemoveFuncIcon").GetComponent<RectTransform>();		mRemoveFuncTip = mTransform.Find("Bottom/Funcs/RemoveBtn/RemoveFuncTip").GetComponent<ShakeRotateLeftRight>();		mCurMoneyBtn = mTransform.Find("Top/CurMoneyBtn").GetComponent<Button>();
            mCurMoneyBtnRect = mTransform.Find("Top/CurMoneyBtn").GetComponent<RectTransform>();		mGamePlayMask = mTransform.Find("GamePlayMask").GetComponent<Image>();		mCurMoneyIcon = mTransform.Find("Top/CurMoneyBtn/CurMoneyIcon").GetComponent<RectTransform>();
        }
    
        protected override void BindButtonEvent() 
        {
            		mWithdrawalBtn.onClick.AddListener( OnWithdrawalBtnClickHandle);		mPrizeDrawBtn.onClick.AddListener( OnPrizeDrawBtnClickHandle);		mTaskBtn.onClick.AddListener( OnTaskBtnClickHandle);		mSettingBtn.onClick.AddListener( OnSettingBtnClickHandle);		mTipBtn.onClick.AddListener( OnTipBtnClickHandle);		mRefushBtn.onClick.AddListener( OnRefushBtnClickHandle);		mRemoveBtn.onClick.AddListener( OnRemoveBtnClickHandle);		mCurMoneyBtn.onClick.AddListener( OnCurMoneyBtnClickHandle);
        }
    
        protected override void UnBindButtonEvent() 
        {
            		mWithdrawalBtn.onClick.RemoveAllListeners();		mPrizeDrawBtn.onClick.RemoveAllListeners();		mTaskBtn.onClick.RemoveAllListeners();		mSettingBtn.onClick.RemoveAllListeners();		mTipBtn.onClick.RemoveAllListeners();		mRefushBtn.onClick.RemoveAllListeners();		mRemoveBtn.onClick.RemoveAllListeners();		mCurMoneyBtn.onClick.RemoveAllListeners();
        }
    
    }
}